### ISSUE TITLE
AddTask page changes

### ISSUE THREAD

**Issue by Chrisharnett** [Brozon3/Maintain#64]
When a new task is added, it should use the stored procedure: 

CALL add_task(description, dueDate, userID, frequency, featureType, applianceType, propertyID, @message_res)

The backend needs to be adjusted to use this procedure.

In the frontend, the user should be able to include a propertyId, featureType,  applianceType.

propertyId be an option (NULL is allowed) from the list of properties attached to the user ( SELECT * from userPropertyView WHERE userID = ?;)

applianceTypes options should be populated from the database.   SELECT applianceType FROM appliances; We should have functionality somewhere to add a new appliance type, perhaps in  the addAppliance flow

featureType is similar to applianceTypes (can be Null). SELECT featureType from features.

**Comment by Brozon3** [comment]
jobs done
